trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa.pub'

- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmSubscriptionId: '9707751e-bb10-42ab-a3b2-cd05593218ae'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'tfbe'
    backendAzureRmResourceGroupLocation: 'East US'
    backendAzureRmStorageAccountName: 'tfberg'
    backendAzureRmContainerName: 'tfbend'
    backendAzureRmKey: '0rIrxXccuT3wY1EpqkwujSpj253n/EgndUjxigS5D28hgSKMpPIstKs0T6YUHogl+ordtDw55FTK+AStHyXGvQ=='
    allowTelemetryCollection: true
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure-resource-manager-service-connection'
    providerAzureRmSubscriptionId: '9707751e-bb10-42ab-a3b2-cd05593218ae'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'
    allowTelemetryCollection: true

- task: TerraformCLI@0
  inputs:
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/configuration/iaac/azure/kubernetes'
    environmentServiceName: 'azure-resource-manager-service-connection'